repos:
  # --- Black (uses Poetry version)
  - repo: local
    hooks:
      - id: black-poetry
        name: black (poetry)
        entry: poetry run black
        language: system
        types: [python]

  # --- Ruff (uses Poetry version)
  - repo: local
    hooks:
      - id: ruff-poetry
        name: ruff (poetry)
        entry: poetry run ruff check --fix
        language: system
        types: [python]

  # --- Mypy (uses Poetry version)
  - repo: local
    hooks:
      - id: mypy-poetry
        name: mypy (poetry)
        entry: poetry run mypy
        language: system
        types: [python]

  # - repo: local
  #   hooks:
  #     - id: python-precommit
  #       name: "Python pre-commit"
  #       entry: poetry run pre-commit
  #       language: system
  #       types: [python]
